steps:
  - task: DownloadPipelineArtifact@1
    displayName: Download signed payload
    inputs:
      buildType: 'current'
      artifactName: 'tmp.macpayload_signed'
      downloadPath: '$(Build.StagingDirectory)/payload'

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.1.x
    inputs:
      packageType: sdk
      version: 3.1.x

  - script: dotnet tool install --global nbgv
    displayName: Install Nerdbank.GitVersioning tool

  - script: nbgv cloud --common-vars
    displayName: Set version variables

  - script: src/osx/Installer.Mac/pack.sh --payload='$(Build.StagingDirectory)/payload' --version='$(GitBuildVersion)' --output='$(Build.StagingDirectory)/pkg/gcmcore-osx-$(GitBuildVersion).pkg'
    displayName: Pack installer payload

  - task: PublishPipelineArtifact@0
    displayName: Upload unsigned package
    inputs:
      artifactName: 'tmp.macinstaller_unsigned'
      targetPath: '$(Build.StagingDirectory)/pkg/gcmcore-osx-$(GitBuildVersion).pkg'
