trigger:
  - master

variables:
  configuration: Release
  winImage: vs2017-win2016
  osxImage: macos-latest

jobs:
- job: windows
  displayName: Windows
  pool:
    vmImage: $(winImage)
  steps:
  - template: templates/windows/compile.yml
  - template: templates/windows/pack.yml

# - job: osx
#   displayName: macOS
#   pool:
#     vmImage: $(osxImage)
#   steps:
#   - template: templates/osx/compile.yml
#   - template: templates/osx/pack.unsigned.yml
