name: "release-homebrew"
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Get macOS package version
      uses: actions/github-script@0.3.0
      id: version
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const release = releases.find(x => x.tag_name === process.env.GITHUB_REF);
          if (!release) {
            throw new Error(`unable to find release with tag '${process.env.GITHUB_REF}'`);
          }
          const regex = /gcmcore-osx-(.*)\.pkg/;
          const asset = release.assets.find(x => regex.test(x.name));
          if (!asset) {
            throw new Error(`unable to find asset matching '${regex}'`);
          }
          const matches = asset.name.match(regex);
          const version = matches[1];
          return version;
    - name: Update Homebrew tap
      uses: mjcheetham/update-homebrew@v1
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: microsoft/git
        name: git-credential-manager-core
        type: cask
        version: ${{ steps.version.outputs.result }}
